# spring:
#   servlet:
#         multipart:
#           max-file-size: 10MB
#           max-request-size: 10MB
#   main:
#     allow-circular-references: true
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/inventory_service
#     username: root
#     password: $env:PASSWORD
#     # url: jdbc:mysql://34.118.232.140:3306/${DB_NAME}
#     # username: ${DB_USERNAME}
#     # password: ${DB_PASSWORD}
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.MySQLDialect
# server:
#   error:
#     include-message: always
#   port: 8082